googleinterns/step188-2020

- .eslintrc.yml
- .github/workflows/csslint.yaml
- .github/workflows/eslint.yaml
- .github/workflows/javabuild.yaml
- .github/workflows/javalint.yaml
- .github/workflows/markdownlint.yaml
- .htmllintrc
- .stylelintrc.json
- package.json
Add linters following Linting Intern Github Project Guide https://docs.google.com/document/d/1JHG2AyEEXUBf1VS4SiIRaNJ5PU-yhpYgkm8XFUuNAbQ/edit.
> Add linters.

- project/src/main/webapp/sps/data/Event.java
#3 
Adds Event class for hardcoded events for Prototype.
Eventually, in the MVP, constructor and all setters and getters will be taken directly from the database.
**Build fails because this Class relies on User and VolunteerOpportunity classes which are not in this PR
> Add Event class

- .prettierc.json
- makefile
- package.json
- Add package dependencies
- Update makefile
> Add auto-formatter tool

- project/src/main/webapp/events-feed.css
- project/src/main/webapp/events-feed.html
- Add UI for events feed
- Used a consistent card design from the event signup
> Add Events Feed UI

- project/src/main/webapp/create-event.html
- project/src/main/webapp/event-details.html
- project/src/main/webapp/events-feed.html
- project/src/main/webapp/header.html
- project/src/main/webapp/script.js
- project/src/main/webapp/signup.html
Adds basic unstyled links for flow between pages.
Highlights appropriate header on navbar.
> Add navigation between pages

- project/src/main/webapp/create-event.html
- project/src/main/webapp/header.css
- project/src/main/webapp/header.html
- project/src/main/webapp/index.css
- project/src/main/webapp/index.html
Restyle header and create home page
Information writing on home page subject to change -- put in place holder text for now. Please comment/edit text as you please for "Tell us about yourself", "Host an Event" and "Discover Events"
Graphics do not belong to us -- currently placeholders / later we can make our own / pick open source ones
New header:
New home page:
> [1/X] Styling header and home page

- project/src/main/webapp/events-feed.css
- project/src/main/webapp/events-feed.html
Restyle Event Discovery page
(Build fails because of missing Java files in master -- will be resolved when User and VolunteeringOpportunity classes pushed)
> [2/Y] Style Event Discovery Page

- project/src/main/java/com/google/sps/servlets/VolunteeringFormHandlerServlet.java
- project/src/main/java/com/google/sps/servlets/VolunteeringOpportunityDataServlet.java
- project/src/main/java/com/google/sps/utilities/DatabaseWrapper.java
- Add servlet and database wrapper method to retrieve single volunteering opportunity.
> [2/Q] Add servlet to retrieve single volunteering opportunity.

- project/src/main/java/com/google/sps/servlets/EventVolunteeringDataServlet.java
- project/src/main/java/com/google/sps/utilities/DatabaseWrapper.java
- Add servlet and database wrapper method to get all volunteering opportunities for given event id.
> [2/Q] Add servlet to get all volunteering opportunities for given event id.

- project/src/main/java/com/google/sps/servlets/VolunteeringFormHandlerServlet.java
- project/src/main/java/com/google/sps/utilities/DatabaseWrapper.java
- project/src/main/webapp/create-volunteering-opportunity.html
- project/src/main/webapp/create-volunteering-opportunity.js
- Add servlet and database wrapper methods for volunteering opportunity update.
- Make naming for volunteering opportunity variables consistent with volunteering opportunity class.
> [2/Q] Add servlet functionality for opportunity update.

- project/src/main/webapp/update-volunteering-opportunity.html
- project/src/main/webapp/update-volunteering-opportunity.js
Add form functionality for volunteering opportunity update.
> [Ready for review] Add form functionality for volunteering opportunity update.

- project/src/test/java/com/google/sps/EventTest.java
Previous event tests disappeared in merge #20 . Added back updated tests.
Build will fail because PR #82 not yet merged, but tests work.
> Add back (revised) Event Tests

- project/pom.xml
- project/src/main/java/com/google/sps/servlets/OpportunitySignupFormHandlerServlet.java
- project/src/main/java/com/google/sps/utilities/SpannerTasks.java
- project/src/main/java/com/google/sps/utilities/TestUtils.java
- project/src/test/java/com/google/sps/OpportunitySignupFormHandlerTest.java
- Add servlet for volunteering opportunity signup form
- Add tests
> [2/X] [Ready for review] Add servlet for signup form.

- project/src/main/java/com/google/sps/servlets/EventCreationServlet.java
- project/src/main/java/com/google/sps/utilities/SpannerTasks.java
- project/src/main/webapp/create-event.html
- project/src/main/webapp/event-details.css
- project/src/main/webapp/event-details.html
- project/src/main/webapp/event-details.js
- project/src/main/webapp/event-edit.html
- project/src/main/webapp/event-edit.js
Exact same changes as: Event editable [Frontend] #98
Changes lost in merge of backend (branched off there), all changes were originally already reviewed in #98 (but then changes all lost) . Build fails because no backend files.
Add edit ability to events after you create them. Redirects to the create event form with the previous form information that you can now change and write back to the db.
> [REVERT] Add back Event Editable frontend

- project/src/main/java/com/google/sps/servlets/VolunteeringOpportunityDataServlet.java
- project/src/test/java/com/google/sps/VolunteeringOpportunityDataTest.java
-Add tests
-Add error checking in servlet to follow tests.
> Add tests for VolunteeringOpportunityDataServlet and add error checking to servlet.

- project/src/test/java/com/google/sps/CommonUtilsTest.java
- project/src/test/java/com/google/sps/OpportunitySignupDataTest.java
- project/src/test/java/com/google/sps/OpportunitySignupFormHandlerTest.java
- project/src/test/java/com/google/sps/OpportunitySignupTasksTest.java
- Change common utils JSON test for new opportunity changes.
- Remove use of stream in OpportunitySignupTasksTest.java
- mvn test result (@Ignore added to EventDetailTest.java)
> [Ready for review] Change common utils JSON test for new opportunity changes.

- project/src/main/java/com/google/sps/servlets/UserProfileUpdateServlet.java
- project/src/main/java/com/google/sps/utilities/TestUtils.java
- project/src/main/webapp/profile-edit.html
- project/src/main/webapp/profile-edit.js
- project/src/main/webapp/shared.js
- project/src/test/java/com/google/sps/UserProfileUpdateTest.java
There was a bug where only the first item was being passed to the DB, so this PR fixes that
> [Ready for review] Fix user profile to DB bug

- project/src/main/webapp/create-volunteering-opportunity.html
- project/src/main/webapp/create-volunteering-opportunity.js
> [Ready for review] Add volopp tags for frontend

- project/src/main/webapp/event-details.html
- project/src/main/webapp/event-details.js
Backend in #110 
Java Build fails because changes in backend.
> Allow Event Registration (Frontend)

- project/src/main/java/com/google/sps/servlets/EventVolunteeringDataServlet.java
- project/src/main/java/com/google/sps/utilities/TestUtils.java
- project/src/test/java/com/google/sps/EventVolunteeringDataTest.java
- Remove hardcoded event ID in EventVolunteeringDataServlet
- Add tests for EventVolunteeringDataServlet
> [1/X] Remove hard-coded event ID and add tests for volunteering data servlet.

- project/src/main/java/com/google/sps/servlets/OpportunitySignupFormHandlerServlet.java
- project/src/main/java/com/google/sps/servlets/VolunteeringFormHandlerServlet.java
- project/src/main/java/com/google/sps/utilities/CommonUtils.java
- project/src/main/java/com/google/sps/utilities/TestUtils.java
- project/src/test/java/com/google/sps/CommonUtilsTest.java
- project/src/test/java/com/google/sps/OpportunitySignupFormHandlerTest.java
- project/src/test/java/com/google/sps/VolunteeringFormHandlerTest.java
- Add test with correct redirect URL for volunteering opportunity form servlet
- Change test for opportunity signup to have correct redirect URL
- Update servlets accordingly
> Change redirect URLs to integrate opportunity with event [back-end]

- project/src/main/java/com/google/sps/servlets/SearchDataServlet.java
- project/src/test/java/com/google/sps/SearchDataServletTest.java
- Use naive algorithm to generate search results
- Add tests
> [1/X] Add servlet to generate search results using naive algorithm.

- project/src/main/java/com/google/sps/servlets/EventRegistrationServlet.java
- project/src/main/webapp/event-card.html
- project/src/main/webapp/event-details.css
- project/src/main/webapp/event-details.html
- project/src/main/webapp/event-details.js
- project/src/main/webapp/events-feed.js
- project/src/main/webapp/shared.js
- project/src/main/webapp/styles.css
> Configure edit and register buttons for hosts and non-hosts

- project/src/main/java/com/google/sps/servlets/EventRankerServlet.java
- project/src/main/webapp/event-details.js
- project/src/main/webapp/events-feed.js
- project/src/main/webapp/shared.js
This PR:
1) Removes the hardcoded events from event ranker
2) That in turn helped fix the bugs where event details header wasn't loaded and labels were being loaded doubly
> Fix event details bug

- project/src/main/webapp/event-card.html
- project/src/main/webapp/events-feed.css
- project/src/main/webapp/events-feed.html
- project/src/main/webapp/events-feed.js
- Use event cards uniform with events feed
- Add search bar at the top of discover events
- Ranking decreases from left to right and top to down
> [2/Y] Add search UI.

- project/src/main/webapp/index.css
- project/src/main/webapp/index.html
Restyle home page
From this (old):
To this (new):
> Restyle homepage

- project/pom.xml
- project/src/main/java/com/google/sps/servlets/EventRankerServlet.java
- project/src/main/java/com/google/sps/utilities/EventRanker.java
- project/src/main/java/com/google/sps/utilities/GetLabelCategories.java
- project/src/test/java/com/google/sps/EventRankerServletTest.java
- project/src/test/java/com/google/sps/EventRankerTest.java
- project/src/test/java/com/google/sps/GetLabelCategoriesTest.java
This PR:
- Connects @yicyao 's labelMapping feature with the event ranking feature to create better weighted scores
- Updates the corresponding ranking (and ranking servlet) unit tests
> [Review for review] Connect ranking and filtering (BACKEND)

- project/src/main/java/com/google/sps/servlets/EventCreationServlet.java
- project/src/main/webapp/event-edit.js
- Currently event ID is not being passed into the mutation so the event is not being updated.
- If eventID is null then we insert event otherwise we update
Must be reviewed by @yicyao before merge
> [1/X] Fix event update.

- project/src/main/webapp/update-volunteering-opportunity.html
- project/src/main/webapp/update-volunteering-opportunity.js
Fix tags double input and first item not visible.
> Fix tags input issue.
